spring:
  application:
    name: microservice-users
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/ms-users}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: 210d3d27605d0ee737952294265400a7cba109746afacd84b9cb0139bf6b7e3a
  expiration-time: 3600000 # 1 hour

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: microservice-users